### ISSUE TITLE
braft noop日志哪里发起的

### ISSUE THREAD

**Issue by daipeixian** [kasshu/braft-docs#1]
你好，非常感谢你写的这篇braft的文档受益匪浅， 我这里在阅读源码之后有个问题：
![image](https://user-images.githubusercontent.com/19338923/110882346-bf7e9900-831c-11eb-9b81-291de8785e37.png)
我找不到braft发起noop log的时机， 在源码里面找了很久也没有发起noop log的代码  所以请教下您noop log究竟是在哪里发起的呢  谢谢

**Comment by kasshu** [comment]
braft没有发起noop log，而是通过写复制组成员日志替代了noop

**Comment by daipeixian** [comment]
> braft没有发起noop log，而是通过写复制组成员日志替代了noop

理解了 非常感谢你的回答
